### ISSUE TITLE
Suggestion table highlights suggestions that have been pre-matched to Wikidata IDs

### ISSUE THREAD

**Issue by rich-cassidy** [mysociety/verification-pages#222]
The table on the verification-page somehow highlights that those which have been pre-matched are good to add to Wikidata if they approved at the verification step.

**Comment by tmtmtmtm** [comment]
I'm assuming this is a "it should do this (but currently doesn't)" rather than an "it currently does this (and shouldn't)", but if so, I don't think this is what we discussed: there really shouldn't *be* a separate step here at all — as soon as data is good to add to Wikidata, it should automatically go.

See also https://github.com/mysociety/verification-pages/issues/180

**Comment by tmtmtmtm** [comment]
oh, hold on, I think I got confused by "matched" here: does that mean "reconciled"? If so, is this really a facet of https://github.com/mysociety/verification-pages/issues/220?

**Comment by tmtmtmtm** [comment]
I believe that this was resolved by the three-row interface
