### ISSUE TITLE
Duplicate P39 created for Dumitru Chiriță

### ISSUE THREAD

**Issue by tmtmtmtm** [mysociety/verification-pages#289]
From [RO:2016](https://www.wikidata.org/wiki/User:Verification_pages_bot/verification/ro/Member_of_the_2016_Chamber_of_Deputies), the entry for Dumitru Chiriță was at Verifiable, and [created](https://www.wikidata.org/w/index.php?title=Q18543845&type=revision&diff=712290748&oldid=699030231) a P39 for his membership of the 2016 term. However, he already had [a P39 for this term, with exactly the same district and group](https://www.wikidata.org/w/index.php?title=Q18543845&oldid=699030231#P39), and this has now [created a duplicate entry](https://www.wikidata.org/w/index.php?title=Q18543845&oldid=712290748#P39)

**Comment by tmtmtmtm** [comment]
It looks like George Ionescu may be in the same state. He's currently appearing on the verification page as needing verified, but [already has a suitable P39](https://www.wikidata.org/wiki/Q21747014#P39).

**Comment by mhl** [comment]
I've done some digging into this, and I believe it's due to the Wikidata Query Service sometimes not returning these people as part of the query for current position holders :disappointed: 

The query being used is: http://tinyurl.com/y9dprubx

Sometimes it returns 1228 results (not including Q21747014 (George Ionescu)) and sometimes it returns 1232 results (including Q21747014). Suggestions for how to deal with that much appreciated... (My only idea is to file a bug in phabricator.)

**Comment by tmtmtmtm** [comment]
This is being tracked as https://phabricator.wikimedia.org/T199916

**Comment by mhl** [comment]
Apparently that was a problem with desynchronization between servers, which they think is now resolved https://phabricator.wikimedia.org/T199916 :

> I've updated relevant entities and looks like the query is consistent now. Please tell me if it happens again.
