### ISSUE TITLE
P39s should not be added to non-humans

### ISSUE THREAD

**Issue by tmtmtmtm** [mysociety/verification-pages#304]
The Wikipedia source behind [LV12](https://www.wikidata.org/wiki/User:Verification_pages_bot/verification/lv/Member_of_the_12th_Saeima) has incorrectly linked Andris Bērziņš to [a disambiguation page](https://www.wikidata.org/wiki/Q238915), rather than the correct item for the person.

In such a case we will still [add a P39 to that page ](https://www.wikidata.org/w/index.php?title=Q238915&type=revision&diff=712749170&oldid=683387131) quite happily.

**Comment by tmtmtmtm** [comment]
My suspicion is that we really want to add a check for P31:Q5 into the query we're using, and where anything is currently reconciled against something *without* that, it should go to the 'manual intervention needed' status for the user to fix that first (potentially by adding 'instance of: human' if it is indeed the correct item, but just missing that)

**Comment by gbp** [comment]
Searching for items during reconciling uses the `wbsearchentities` [1] API endpoint which doesn't allow us to filter disambiguation items. So looks like we need a Rails endpoint which will perform another SPARQL query [2] to get this information which will allow the frontend app to filter the results. Going to ignore the fact this will break the pagination

The later on we check the person is a human [3] when retrieving existing statements. Is isn't optional so I don't think we would get any statements if a person had already been reconciled to disambiguation item - as happened with Andris Bērziņš. This probably allows multiple duplicate P39 to be created too.

In order to prevent P39 on disambiguation items, and considering items with CSV source might already be reconciled, we need to double check the items when classifying statements by updating the SPARQL and check when working out the `statement.type` [4]. This could happen in the `membership-comparison` gem if deemed appropriate.

[1] https://www.wikidata.org/w/api.php?action=help&modules=wbsearchentities
[2] https://www.wikidata.org/wiki/Wikidata:SPARQL_query_service/queries/examples#Disambiguation_pages_entities_used_as_publishers
[3] https://github.com/mysociety/verification-pages/blob/d92cb9f227e6f08ccfd1d8c980473e787fbbdb43/app/services/retrieve_position_data.rb#L40
[4] https://github.com/mysociety/verification-pages/blob/d92cb9f227e6f08ccfd1d8c980473e787fbbdb43/app/services/statement_classifier.rb#L81-L101

**Comment by gbp** [comment]
http://tinyurl.com/ybnhz2jy shows a number of disambiguation items with P39s - none seem to be due to actions from Verification Pages

**Comment by gbp** [comment]
> So looks like we need a Rails endpoint which will perform another SPARQL query [2] to get this information which will allow the frontend app to filter the results.

Initially I'm not going worry about this filtering. For now we'll display a conflict and the user can re-reconcile to fix so its not a big issue.
