### ISSUE TITLE
Aldis Adamovičs is reconciled, but not linked to Wikidata

### ISSUE THREAD

**Issue by tmtmtmtm** [mysociety/verification-pages#305]
In [LV12](https://www.wikidata.org/wiki/User:Verification_pages_bot/verification/lv/Member_of_the_12th_Saeima) the top statement claims to have been actioned but reverted. That implies that we know the Wikidata ID for Aldis Adamovičs, yet his name here isn't a link.

![screen shot 2018-07-19 at 10 52 23](https://user-images.githubusercontent.com/57483/42935612-f55076dc-8b41-11e8-956a-9333232d7dea.png)

**Comment by mhl** [comment]
I think what's happening here is that there's a cron job that goes back every day to check the CSV source, and update the `statements` table in the verification-pages database. If there's no `person_item` in the CSV source, but there is one that was added by reconciliation, that update process is then clearing it. Fortunately, there is a record of all the reconciliations that have been done in the `reconciliations` table, so we can recover from this.

My suggested course of action is the following:

- [ ] Change the [run method of load statements](https://github.com/mysociety/verification-pages/blob/5659e2c6dc4a07c0c02181969b9670bf5a436ffb/app/services/load_statements.rb), to stop it replacing a non-blank `person_item`, `electoral_district_item` or `parliamentary_group_item` with a blank one. (If there's non-blank `*_item` coming from the CSV, it should overwrite the one in the statement row, however, since one of the uses of this tool is to show differences between the source and what's in Wikidata, even if the source changes, or now has a value that contradicts manual reconciliation.) Deploy that change, so the cron job is safe again.
- [ ] Write a rake task that goes through each `Reconciliation` (in chronological order) and calls `update_statement` on it (either by making that method public, or triggering the `after_commit` hook). (That should restore the historic reconciliation data.)

I think that's all that's need to fix this, but it'd be good for @chrismytton to check this plan.

**Comment by chrismytton** [comment]
@mhl Those steps look sensible to me 👍

**Comment by mhl** [comment]
OK, I've done those steps and Aldis Adamovičs has his item back, so I'm closing this.
