### ISSUE TITLE
Name changes aren't being reported back to Rails

### ISSUE THREAD

**Issue by gbp** [mysociety/verification-pages#439]
This means they aren't being forwarded on to Suggestion store.

Was broken when name changes moved to the reconciliation step in #355

**Comment by mhl** [comment]
This is as designed - really what those "name changes" were for either (a) supplying a different string for the reconciliation search and (b) the label a person would be given if you created them in the interface. We do both of these in a more flexible way now, where you're not really changing a name, you're just able to put in whatever search string you like. (And optionally you can use that string to create the person.)

The other thing the name correction feature was used for was to provide a subtly different signal back to Facebook about whether a name was completely correct or slightly mispelled, but for a number of reasons we don't think this distinction was clear or useful, so now we've effectively dropped the "corrected" status we feed back.

I suppose I should have also made a PR to drop the `new_name` column from `verifications` to make this clear, but I think I was reluctant to do that in case this turned out to be a mistake and we'd thrown away that data. We could just archive it just in case and drop the column now, though, I think.

**Comment by gbp** [comment]
Okay this all makes sense. Closing in favour of #452.
