### ISSUE TITLE
(v2) Open multi-period P39 gets incorrectly amended

### ISSUE THREAD

**Issue by tmtmtmtm** [mysociety/verification-pages#504]
Given a [still-current membership](https://www.wikidata.org/w/index.php?title=Q119880&oldid=772750074#P39), starting several terms ago:

![screen shot 2018-10-25 at 11 49 34](https://user-images.githubusercontent.com/57483/47495455-1b2f5100-d84c-11e8-840d-4df2ce705b47.png)

Verifying that this person is a member of the 50th Federal Assembly [takes over the existing statement, creating inconsistent data](https://www.wikidata.org/w/index.php?title=Q119880&type=revision&diff=772749404&oldid=718778321):

![screen shot 2018-10-25 at 11 51 36](https://user-images.githubusercontent.com/57483/47495559-592c7500-d84c-11e8-91d1-db8d7dbfe8fc.png)

**Comment by gbp** [comment]
This appears to have happened because https://github.com/everypolitician/membership-comparison/blob/master/spec/membership_comparison_spec.rb#L226-L243 as this is a partial match. Differences here are:
1. a larger duration between statement start and the term start
2. term has an end date.

Should we change this spec to be a conflict or add another case for one of the above issues?

**Comment by tmtmtmtm** [comment]
@gbp the existing spec is correct, as the case described in https://github.com/mysociety/verification-pages/issues/236

The case described in _this_ issue should be caught by the 'EOPT' checks in the approach @mhl and I mapped out.

**Comment by gbp** [comment]
@tmtmtmtm so I'm thinking we need to pass in the EPOT/SONT dates into comparison gem which would allow us to get these changes passing: https://github.com/everypolitician/membership-comparison/compare/started-before-eopt

**Comment by gbp** [comment]
To support this we need to change the SPARQL query fetching the term data: https://github.com/mysociety/verification-pages/compare/504-multi-period-p39s
