### ISSUE TITLE
Allow all configuration to be set on the Page, not only on the Country

### ISSUE THREAD

**Issue by tmtmtmtm** [mysociety/verification-pages#531]
There is pretty much nothing about a Page that can be assumed to be the same for all Pages in the same country — we can easily have a great many verification pages across all the different legislatures (and history of them) in a country, against multiple sources, each of which are in different languages, etc.

Moving all the configuration to the Page, rather than the Country, and having all pages be created directly on-wiki, would not only solve a variety of open issues (e.g. #530 #401 #402 #459 #458 #498 #293 #290 #138 #139), but it would also make it possible for normal users to configure these, rather that only admins.

**Comment by gbp** [comment]
From a conversation the other day we said we would try derive the country from the position held item passed in from the template tag as described in #459. To do this and to fix the some of the other issues linked above we need to:

For #401 

- [ ] move the `label_lang` from the Country model to the Page model
- [ ] accept `label_lang` from wiki template tag

For #530 

- [ ] double check the current `Country#description_en` values have been migrated to `Page#new_item_description_en`
- [ ] remove and delegation to the old column

#458 / #459

- [ ] add `Page#country_item` string column
- [ ] add `Page#country_item` to new page form
- [ ] add `Page#country_name` string column
- [ ] add `Page#country_item` and `Page#country_name` to Page show and index views
- [ ] migrate existing `Country#code` values have been migrated to `Page#country_item`
- [ ] migrate existing `Country#name` values have been migrated to `Page#country_name`
- [ ] add Page validation to ensure if a page has `hash_epoch == 2` then an ISO country code item is valid - EG 2 or 3 characters
- [ ] change statement transaction ID generation hash from `{ country: country.code, ... }` to `{ country: page.country, ... }` - doesn't need a hash epoch increase as fields have been migrated to Page model
- [ ] ensure all parts of the code now use `Page#country_item`,  `Page#country_name`, `Page#new_item_description_en` and `Page#label_lang` instead of referencing the `Page#country...` or `Page#country_id` - check statistic pages
- [ ] drop the `Page#country_id` and association
- [ ] drop the Country model and database table
- [ ] increase statement transaction ID hash epoch - so we can differentiate Pages with ISO like country codes and those with Q-IDs
- [ ] add Page validation to ensure if a page has `hash_epoch == 3` then an Q-ID country item is valid
- [ ] optional - setup automatic loading of `country_name`, like how `position_held_name`, `parliamentary_term_name` are retrieved from a SPARQL query - so we have countries names for new Verification Pages
- [ ] store the position held item's country property (P17) as `Page#country_item`
- [ ] show warning when the given position held item doesn't have a country property, and ask the user to correct it on Wikidata before continuing.

This would make #402 #498 #290 obsolete.

**Comment by gbp** [comment]
Going to close this issue as main points have now been resolved. The linked issues still open are: #293 #138 #139

**Comment by tmtmtmtm** [comment]
Woohoo!

It's probably worth also updating the [Bot Request](https://www.wikidata.org/wiki/Wikidata:Requests_for_permissions/Bot/Verification_pages_bot) in light of this too.

**Comment by gbp** [comment]
Yep, in the process of updating the template docs too.
