### ISSUE TITLE
Be more liberal in the CSV column names we accept

### ISSUE THREAD

**Issue by chrismytton** [mysociety/verification-pages#534]
At the moment the column names in the CSV source have to be exactly what we expect. It would be good if we were a bit more flexible and allowed multiple names for the same column.

This would specifically be useful for migrating EveryPolitician to use Wikidata. Ideally we would be able to point at legislative period CSVs on EveryPolitician's `master` branch directly.

**Comment by gbp** [comment]
Proposed mappings:

```electoral_district_item: area_id
electoral_district_item: area_wikidata
electoral_district_item: wikidata_area
electoral_district_item: constituency_id
electoral_district_item: constituency_wikidata
electoral_district_item: district_id

electoral_district_name: area
electoral_district_name: constituency

parliamentary_group_item: alliance_id
parliamentary_group_item: coalition_id
parliamentary_group_item: faction_id
parliamentary_group_item: party_id
parliamentary_group_item: party_wikidata
parliamentary_group_item: wikidata_group

parliamentary_group_name: alliance
parliamentary_group_name: coalition
parliamentary_group_name: faction
parliamentary_group_name: party
parliamentary_group_name: group

person_item: id
person_item: wikidata

person_name: name```

**Comment by tmtmtmtm** [comment]
#539 didn't achieve the goal of being able to load the EP term CSVs:

https://www.wikidata.org/wiki/User:Verification_pages_bot/verification/bz/Member_of_the_9th_House_of_Representatives, with a setup of:

```
{{Verification_page
|position_held_item=Q21290854
|parliamentary_term_item=Q58873353
|country_code=bz
|csv_source_url=https://raw.githubusercontent.com/everypolitician/everypolitician-data/master/data/Belize/Representatives/term-9.csv
}}
```
seems to have mapped the UUIDs rather than the Wikidata Qids:

![screen shot 2018-11-19 at 16 16 32](https://user-images.githubusercontent.com/57483/48719937-85060500-ec16-11e8-87a5-9eeddc439872.png)
